# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addProductDialog.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(480, 320)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.label_1 = QtWidgets.QLabel(Dialog)
        self.label_1.setObjectName("label_1")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_1)
        self.productName = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.productName.sizePolicy().hasHeightForWidth())
        self.productName.setSizePolicy(sizePolicy)
        self.productName.setMaxLength(50)
        self.productName.setObjectName("productName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.productName)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.caloricity = QtWidgets.QLineEdit(Dialog)
        self.caloricity.setMaxLength(7)
        self.caloricity.setObjectName("caloricity")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.caloricity)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.proteins = QtWidgets.QLineEdit(Dialog)
        self.proteins.setMaxLength(7)
        self.proteins.setObjectName("proteins")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.proteins)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.fats = QtWidgets.QLineEdit(Dialog)
        self.fats.setMaxLength(7)
        self.fats.setObjectName("fats")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.fats)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.carbohydrate = QtWidgets.QLineEdit(Dialog)
        self.carbohydrate.setMaxLength(7)
        self.carbohydrate.setObjectName("carbohydrate")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.carbohydrate)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.weightOfPack = QtWidgets.QLineEdit(Dialog)
        self.weightOfPack.setMaxLength(7)
        self.weightOfPack.setObjectName("weightOfPack")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.weightOfPack)
        self.weightOfPeace = QtWidgets.QLineEdit(Dialog)
        self.weightOfPeace.setMaxLength(7)
        self.weightOfPeace.setObjectName("weightOfPeace")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.weightOfPeace)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.delButton = QtWidgets.QPushButton(Dialog)
        self.delButton.setObjectName("delButton")
        self.horizontalLayout_2.addWidget(self.delButton)
        self.addButton = QtWidgets.QPushButton(Dialog)
        self.addButton.setObjectName("addButton")
        self.horizontalLayout_2.addWidget(self.addButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_1.setText(_translate("Dialog", "Название:"))
        self.label_2.setText(_translate("Dialog", "Калорийность:"))
        self.label_3.setText(_translate("Dialog", "Белки:"))
        self.label_4.setText(_translate("Dialog", "Жиры:"))
        self.label_5.setText(_translate("Dialog", "Углеводы:"))
        self.label_6.setText(_translate("Dialog", "Вес упаковки"))
        self.label_7.setText(_translate("Dialog", "Вес штуки"))
        self.delButton.setText(_translate("Dialog", "Удалить"))
        self.addButton.setText(_translate("Dialog", "Сохранить"))

